# -*- coding: utf-8 -*-
"""shark_finning ai

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1091KMIJZBvg6rp9H5SFsJFd_PxbSRyJr
"""

# Install YOLOv8 and Roboflow
!pip install -q ultralytics roboflow

import zipfile
import os

zip_path = "/content/Shark Species Dataset.v4i.yolov8 (2).zip"  # exact file name
extract_path = "/content/shark_species_dataset"

# Unzip the dataset
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Verify contents
os.listdir(extract_path)

data_yaml_path = "/content/shark_species_dataset/data.yaml"

with open(data_yaml_path, 'r') as file:
    data = file.read()

# Replace relative paths with absolute paths
data = data.replace("../train/images", "/content/shark_species_dataset/train/images")
data = data.replace("../valid/images", "/content/shark_species_dataset/valid/images")
data = data.replace("../test/images", "/content/shark_species_dataset/test/images")

with open(data_yaml_path, 'w') as file:
    file.write(data)

# Confirm YAML looks good
!cat /content/shark_species_dataset/data.yaml

from ultralytics import YOLO

# Load pre-trained model (nano = fastest, try yolov8s.pt for better accuracy)
model = YOLO("yolov8n.pt")

# Train
model.train(
    data="/content/shark_species_dataset/data.yaml",
    epochs=30,
    imgsz=640,
    batch=16,
    project="FinShield",
    name="shark_finning_ai"
)

metrics = model.val()

"""# New Section"""

!pip install ultralytics

import zipfile
import os

# Define zip path and extraction path
zip_path = "/content/Shark Species Dataset.v1i.yolov8.zip"
extract_path = "/content/shark_dataset"

# Unzip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Confirm contents
print("Extracted files:", os.listdir(extract_path))

from ultralytics import YOLO

yaml_path = "/content/shark_dataset/data.yaml"

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data=yaml_path,
    epochs=50,
    imgsz=640,
    batch=16,
    name="finshield_yolov8n"
)

!pip install ultralytics

import zipfile
import os

zip_path = "//Marine - Sharks - Synthetic.v1i.yolov8.zip"
extract_path = "/content/shark_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipped dataset to:", extract_path)


yaml_path = os.path.join(extract_path, "data.yaml")

# Confirm it's there
if os.path.exists(yaml_path):
    print("Found data.yaml ✅")
else:
    raise FileNotFoundError("❌ data.yaml not found! Check folder structure.")


from ultralytics import YOLO

# Load the pre-trained base model
model = YOLO("yolov8n.pt")  # or yolov8s.pt if you want slightly better accuracy

# Train
model.train(
    data=yaml_path,
    epochs=50,
    imgsz=640,
    batch=8,
)